apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
spec:
  selector:
    matchLabels:
      app: MenuItemListing
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: MenuItemListing
        image: menuitemrg.azurecr.io/containerrp:latest
        ports:
        - containerPort: 8080
