apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemlisting-deployment
spec:
  selector:
    matchLabels:
      app: menuitemlisting
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: menuitemlisting
    spec:
      containers:
      - name: menuitemlisting
        image: menuitemrg.azurecr.io/containerrp:latest
        ports:
        - containerPort: 8080
        imagepullsecret :
         - name: menussecret

---
apiVersion: v1
kind: service
metadata:
 name: menuitemlist
 labels:
 app: menuitemlisting
spec:
 type: LoadBalancer
 ports:
 - port: 80
 
 selector:
 app: MenuItemListing

